-- 1. CRIACAO DAS TABELAS PRINCIPAIS
CREATE TABLE CLIENTES (
    CLI_ID INTEGER NOT NULL,
    CLI_NOME VARCHAR(30) NOT NULL,
    CLI_SALDO DECIMAL(9,0) NOT NULL,
    DT_ATUALIZACAO DATE,
    PRIMARY KEY (CLI_ID)
);

CREATE TABLE TRANSACOES (
    TRX_ID INTEGER NOT NULL,
    CLI_ID INTEGER NOT NULL,
    TRX_TIPO CHAR(1) NOT NULL,
    TRX_VALOR DECIMAL(9,0) NOT NULL,
    DT_PROCESSAMENTO DATE,
    PRIMARY KEY (TRX_ID)
);

CREATE TABLE ERROS_PROCESSAMENTO (
    ID_ERRO INTEGER GENERATED ALWAYS AS IDENTITY,
    CLI_ID INTEGER,
    DESCRICAO_ERRO VARCHAR(100),
    DT_OCORRENCIA TIMESTAMP,
    PRIMARY KEY (ID_ERRO)
);

-- 2. DESAFIOS EXTRAS: OTIMIZACAO E HISTORICO
CREATE INDEX IDX_TRANSACOES_CLI ON TRANSACOES(CLI_ID);

CREATE TABLE HISTORICO_TRANSACOES (
    HIST_ID INTEGER GENERATED ALWAYS AS IDENTITY,
    CLI_ID INTEGER,
    TRX_ID INTEGER,
    TIPO_MOVIMENTO CHAR(1),
    VALOR DECIMAL(9,0),
    DT_REGISTRO TIMESTAMP,
    PRIMARY KEY (HIST_ID)
);

-- 3. TRIGGER AUTOMATIZADA
CREATE TRIGGER TRG_HIST_TRX
AFTER INSERT ON TRANSACOES
REFERENCING NEW AS N
FOR EACH ROW
BEGIN ATOMIC
    INSERT INTO HISTORICO_TRANSACOES (CLI_ID, TRX_ID, TIPO_MOVIMENTO, VALOR, DT_REGISTRO)
    VALUES (N.CLI_ID, N.TRX_ID, N.TRX_TIPO, N.TRX_VALOR, CURRENT TIMESTAMP);
END;